export const FETCH_START ="FETCH_ORDERS_START"
export const FETCH_SUCCESS ="FETCH_ORDERS_SUCCESS"
export const FETCH_FAIL ="FETCH_ORDERS_FAIL"

export const AUTH_START = "AUTH_START"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAIL = "AUTH_FAIL"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST"
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS"
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE"

export const GET_CURRENT_BOOTCAMP_REQUEST = "GET_CURRENT_BOOTCAMP_REQUEST"
export const GET_CURRENT_BOOTCAMP_SUCCESS = "GET_CURRENT_BOOTCAMP_SUCCESS"
export const GET_CURRENT_BOOTCAMP_FAILURE = "GET_CURRENT_BOOTCAMP_FAILURE"

export const GET_CURRENT_COURSES_REQUEST = "GET_CURRENT_COURSES_REQUEST"
export const GET_CURRENT_COURSES_SUCCESS = "GET_CURRENT_COURSES_SUCCESS"
export const GET_CURRENT_COURSES_FAILURE = "GET_CURRENT_COURSES_FAILURE"
